### ISSUE TITLE
Resource don't load via Direct Connect

### ISSUE THREAD

**Issue by JokarLP** [chrismin13/AdditionsAPI#43]
I don't know if it is possible to fix this but if User join via direct connect the force Option won't work and the ResourcePack don't load for the user. Same Problem for ModelAPI

**Comment by vibrantrida** [comment]
are you using minepack? try this `config.yml`:
```yml
resource-pack:
  use-minepack: false
  send-to-player: true
  force-on-join: false
  overwrite-files: true
```
**Don't forget to portforward the port set under `http`**!

If this didn't work, set `send-to-player` to `false then upload the generated resource pack to a file host like dropbox then use the URL in your `server.properties`.
